### PR TITLE
Home Page - Responsive Design and Styling Fix

### LINKED ISSUE #55: Home Page - Button (Sign In) Styling Issue
**Describe the bug**

Currently, when you hover over or press the `Sign In` button, the text disappears.

**To Reproduce**
1. Go to 'http://localhost:3000'
2. Click on 'Sign In' Button
3. See that upon hovering or clicking the text disappears.

**Expected behavior**

I expect the button text to not disappear. I expect it to remain readable.

**Screenshots**

Home Page Sign In Button

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] Safari
 - Version [e.g. 22] Latest

**Additional context**

This is likely an issue of `css styling` being applied to elements not meant to be styled. A fix would be to be more explicit with css styling, and not selecting all `links` but only certain `links` with `className="x"`

### LINKED ISSUE #56: Home Page - Responsive Design
**Describe the bug**

Currently the Home Page is not quite responsive. 

**To Reproduce**
1. Go to 'http://localhost:3000'
2. Resize Browser

**Expected behavior**

I expect the design to be responsive. 

**Screenshots**

Capture d’écran, le 2020-05-22 à 11 14 17
Capture d’écran, le 2020-05-22 à 11 15 06

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] Safari
 - Version [e.g. 22] Latest

**Additional context**

We will need to re-think the design a little bit for the Home Page and redo the styling so when the browser resizes the contents remain visible.

### PR DESCRIPTION
**Pull request by FlyteWizard**
## Changes

* Closes: #55 
* Closes: #56

### CODE REVIEW

**Comment by FlyteWizard** [comment]
# Visual Changes Demo

Home Page - SignInForm - Large Screens


Home Page - SignInForm - Medium Screens


Home Page - SignInForm - Small Screens (With Hover)


Home Page - SignUpForm - Large Screens


Home Page - SignUpForm - Medium Screens


Home Page - SignUpForm - Small Screens

**Comment by FlyteWizard** [comment]
TODO:
* Verify Language (Buttons, Text)

**Comment by FlyteWizard** [comment]
Sign In Form
Sign In Form

Sign Up Form
Sign Up Form

**Review by rmcilwain6 — APPROVED** [review]

**Review by Gohsato — APPROVED** [review]
Looks great 👍 
I've never used `rem` before, but it seems way better for accessibility! I would be really interested in hearing about where you picked up the practice.

**Comment by FlyteWizard** [comment]
> I've never used `rem` before, but it seems way better for accessibility! I would be really interested in hearing about where you picked up the practice.

Yes, Material-UI uses `rem`. `rem` let's users change the base font-size and therefore all other font-sizes on the page.

I started the practice during my first co-op, we used it on all our designs.

**Pull request merged**
